name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
      - name: Build Artifacts
        run: |
          sudo apt install -y libudev-dev pkg-config libxdo-dev
          cargo build --verbose --release
          mv target/release/xboxdriver ./xboxdriver
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xboxdriver
          path: xboxdriver
